# TASYIIR - online demo server on this PC, published with a free Cloudflare
# quick tunnel. Runs the app from this repository in hosted mode with the
# demo switched on (.env.demo + its own database in demo-server\), so the
# development .env and database are never touched.
#
#   start-demo.bat          start (first run asks for WhatsApp + admin login)
#   stop-demo.bat           stop the server and the tunnel
#
# Everything the demo creates lives in demo-server\ and .env.demo, both
# ignored by git and excluded from the client release zips.

param([switch]$Stop, [int]$Port = 8090)

$ErrorActionPreference = 'Stop'
$Root = (Resolve-Path (Join-Path $PSScriptRoot '..\..')).Path
$Dir = Join-Path $Root 'demo-server'
$EnvFile = Join-Path $Root '.env.demo'
$Db = Join-Path $Dir 'demo.sqlite'
$Ini = Join-Path $Dir 'php.ini'
$Cf = Join-Path $Dir 'cloudflared.exe'
$PidFile = Join-Path $Dir 'pids.txt'
$LinkFile = Join-Path $Dir 'LIEN-DEMO.txt'
$TunnelLog = Join-Path $Dir 'tunnel.log'

function Say($text, $color = 'Gray') { Write-Host $text -ForegroundColor $color }
function Fail($text) { Say "[X] $text" Red; exit 1 }

function Stop-Demo {
    if (Test-Path $PidFile) {
        foreach ($id in (Get-Content $PidFile)) {
            $p = Get-Process -Id ([int]$id) -ErrorAction SilentlyContinue
            if ($p -and ($p.ProcessName -in @('php', 'cloudflared'))) { Stop-Process -Id $p.Id -Force -ErrorAction SilentlyContinue }
        }
        Remove-Item $PidFile -Force -ErrorAction SilentlyContinue
    }
}

if ($Stop) { Stop-Demo; Say 'Demo arretee.' Green; exit 0 }

New-Item -ItemType Directory -Force -Path $Dir | Out-Null
Stop-Demo   # a previous run whose window was closed

# --- PHP ----------------------------------------------------------------------
$Php = Join-Path $Root 'scripts\php-runtime\php.exe'
if (-not (Test-Path $Php)) {
    $cmd = Get-Command php -ErrorAction SilentlyContinue
    if (-not $cmd) { Fail 'PHP introuvable (scripts\php-runtime\php.exe).' }
    $Php = $cmd.Source
}
$PhpDir = Split-Path $Php
if (-not (Test-Path $Ini)) {
@"
; generated by scripts\demo\demo.ps1
extension_dir = "$PhpDir\ext"
extension=pdo_sqlite
extension=sqlite3
extension=gd
extension=zip
extension=mbstring
extension=fileinfo
extension=openssl
extension=sodium
extension=curl
extension=intl
variables_order = "GPCS"
memory_limit = 512M
max_execution_time = 120
upload_max_filesize = 64M
post_max_size = 64M
date.timezone = Africa/Casablanca
display_errors = Off
log_errors = On
opcache.enable = 1
"@ | Set-Content -Path $Ini -Encoding ascii
}

# Every artisan call and the web server read .env.demo instead of .env.
$env:APP_ENV = 'demo'
function Artisan([string[]]$params) {
    & $Php -c $Ini (Join-Path $Root 'artisan') @params --no-ansi
    if ($LASTEXITCODE -ne 0) { Fail ("php artisan " + ($params -join ' ') + ' a echoue.') }
}

# --- first run: .env.demo -----------------------------------------------------
if (-not (Test-Path $EnvFile)) {
    Say ''
    Say '=== Premiere configuration de la demo ===' Cyan
    $wa = Read-Host 'Votre numero WhatsApp pour les clients (ex: 0612345678)'
    $wa = ($wa -replace '\D', '')
    if ($wa.StartsWith('0')) { $wa = '212' + $wa.Substring(1) }
    $bytes = New-Object byte[] 32
    [Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($bytes)
    $key = 'base64:' + [Convert]::ToBase64String($bytes)
@"
APP_NAME=TASYIIR
APP_ENV=demo
APP_KEY=$key
APP_DEBUG=false
APP_URL=http://127.0.0.1:$Port
APP_TIMEZONE=Africa/Casablanca
APP_LOCALE=ar
APP_FALLBACK_LOCALE=en

# Online demo: public free-trial signup, 7 days per center.
TASYIIR_MODE=saas
TASYIIR_SIGNUP_REQUIRES_APPROVAL=false
TASYIIR_DEMO=true
TASYIIR_DEMO_DAYS=7
TASYIIR_DEMO_WHATSAPP=$wa
TASYIIR_DEMO_PRICE="500 DH"
TASYIIR_TRUSTED_PROXIES=*

DB_CONNECTION=sqlite
DB_DATABASE='$Db'

SESSION_DRIVER=database
SESSION_LIFETIME=600
CACHE_STORE=database
QUEUE_CONNECTION=sync
MAIL_MAILER=log
LOG_CHANNEL=single
LOG_LEVEL=error
BCRYPT_ROUNDS=12
"@ | Set-Content -Path $EnvFile -Encoding ascii
    Say 'Configuration enregistree dans .env.demo' Green
}

# --- database (created + migrated on every start, data kept) ------------------
$firstDb = -not (Test-Path $Db)
if ($firstDb) { New-Item -ItemType File -Path $Db | Out-Null }
Artisan @('config:clear')
Artisan @('migrate', '--force')

if ($firstDb) {
    Say ''
    Say '=== Votre compte administrateur (pour voir les centres inscrits) ===' Cyan
    $email = Read-Host 'Email'
    $name = Read-Host 'Nom'
    $sec = Read-Host 'Mot de passe (8 caracteres minimum)' -AsSecureString
    $plain = [Runtime.InteropServices.Marshal]::PtrToStringAuto([Runtime.InteropServices.Marshal]::SecureStringToBSTR($sec))
    & $Php -c $Ini (Join-Path $Root 'artisan') make:platform-admin $email $name $plain --no-ansi
    $plain = $null
    if ($LASTEXITCODE -ne 0) { Remove-Item $Db -Force; Fail 'Compte administrateur non cree. Relancez start-demo.bat.' }
}

# --- cloudflared ----------------------------------------------------------------
if (-not (Test-Path $Cf)) {
    Say 'Telechargement de cloudflared (une seule fois, ~60 Mo)...'
    [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
    $ProgressPreference = 'SilentlyContinue'
    Invoke-WebRequest 'https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-windows-amd64.exe' -OutFile $Cf -UseBasicParsing
}

# --- web server ----------------------------------------------------------------
$server = Join-Path $Root 'vendor\laravel\framework\src\Illuminate\Foundation\resources\server.php'
$web = Start-Process -FilePath $Php -WorkingDirectory (Join-Path $Root 'public') -WindowStyle Hidden -PassThru `
    -ArgumentList @('-c', "`"$Ini`"", '-S', "127.0.0.1:$Port", "`"$server`"")

$up = $false
for ($i = 0; $i -lt 30 -and -not $up; $i++) {
    Start-Sleep -Milliseconds 500
    try { $c = New-Object Net.Sockets.TcpClient; $c.Connect('127.0.0.1', $Port); $c.Close(); $up = $true } catch {}
}
if (-not $up) { Stop-Process -Id $web.Id -Force -ErrorAction SilentlyContinue; Fail "Le serveur ne demarre pas (port $Port deja utilise ?)." }

# --- tunnel --------------------------------------------------------------------
Remove-Item $TunnelLog -Force -ErrorAction SilentlyContinue
$tunnel = Start-Process -FilePath $Cf -WindowStyle Hidden -PassThru -RedirectStandardError $TunnelLog `
    -ArgumentList @('tunnel', '--no-autoupdate', '--url', "http://127.0.0.1:$Port")
Set-Content -Path $PidFile -Value @($web.Id, $tunnel.Id)

$url = $null
for ($i = 0; $i -lt 60 -and -not $url; $i++) {
    Start-Sleep -Seconds 1
    if (Test-Path $TunnelLog) {
        # cloudflared still has the log open: read it with a shared handle.
        try {
            $fs = [IO.File]::Open($TunnelLog, 'Open', 'Read', 'ReadWrite')
            $text = (New-Object IO.StreamReader($fs)).ReadToEnd()
            $fs.Close()
            $m = [regex]::Match($text, 'https://(?!api\.)[a-z0-9-]+\.trycloudflare\.com')
            if ($m.Success) { $url = $m.Value }
        } catch {}
    }
}
if (-not $url) { Stop-Demo; Fail "Le tunnel Cloudflare n'a pas donne de lien. Verifiez Internet (journal : demo-server\tunnel.log)." }

# Opening the link before the tunnel is registered makes Windows cache a
# "site not found" answer for that name, so wait for the connection first.
for ($i = 0; $i -lt 30; $i++) {
    try {
        $fs = [IO.File]::Open($TunnelLog, 'Open', 'Read', 'ReadWrite')
        $text = (New-Object IO.StreamReader($fs)).ReadToEnd()
        $fs.Close()
        if ($text -match 'Registered tunnel connection') { break }
    } catch {}
    Start-Sleep -Seconds 1
}
Start-Sleep -Seconds 3

$share = "$url/register-center"
@"
Lien a partager (essai gratuit 7 jours) :
$share

Votre espace admin (centres inscrits + leurs numeros) :
$url/admin

Ce lien change a chaque redemarrage de la demo.
"@ | Set-Content -Path $LinkFile -Encoding utf8
try { Set-Clipboard -Value $share } catch {}

Say ''
Say '==============================================================' Green
Say '  DEMO EN LIGNE' Green
Say '==============================================================' Green
Say ''
Say '  Lien a partager (copie dans le presse-papiers) :'
Say "  $share" Yellow
Say ''
Say '  Votre espace admin :'
Say "  $url/admin" Cyan
Say ''
Say '  Gardez ce PC allume et connecte.'
Say '  Pour arreter : appuyez sur Entree ici (ou lancez stop-demo.bat).'
Say ''
Start-Process "$url/admin"

try { [void](Read-Host) } finally { Stop-Demo; Say 'Demo arretee.' Green }
